TAI_Forum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TAI_Forum.Infrastructure;
using TAI_Forum.Models;

namespace TAI_Forum.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string message = null)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            var th = client.GetAllThreads().OrderByDescending(o => o.Item5.ToDate());
            
            List<IndexModel.SingleThread> tList = new List<IndexModel.SingleThread>();
            foreach (var t in th)
                tList.Add(new IndexModel.SingleThread() { Id = t.Item1, Topic = t.Item2, ContentLead = t.Item3, Tags = t.Item4, Author = t.Item6 });

            IndexModel model = new IndexModel() { ThreadsList = tList };
            if (message != null)
                model.IndexMessage = message;

            return View("Index", model);
        }

        public ViewResult SearchForTag(string tag)
        {
            List<SearchModel.SingleSearchThread> tList = new List<SearchModel.SingleSearchThread>();
            DatabaseAccess client = DatabaseAccess.Instance;
            

            var th = client.GetAllThreads(tag);
            foreach (var t in th)
                tList.Add(new SearchModel.SingleSearchThread() { Id = t.Item1, Topic = t.Item2, ContentLead = t.Item3, Tags = t.Item4, Author = t.Item6 });

            SearchModel model = new SearchModel() { SearchThreadsList = tList, Tag = tag };

            return View("SearchResult", model);
        }
    }
}

TAI_Forum/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TAI_Forum.Models;
using TAI_Forum.Infrastructure;

namespace TAI_Forum.Controllers
{
    public class ThreadsController : Controller
    {
        public ViewResult DisplayNewThread()
        {
            return View("NewThread", new NewThreadModel());
        }

        public ActionResult CreateNewThread(NewThreadModel model)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            if (model.Topic == null)
                ModelState.AddModelError("", "Brak nazwy wątku!");
            if (model.Content == null)
                ModelState.AddModelError("", "Treść nie może być pusta");
            if (ModelState.Values.SelectMany(s => s.Errors).Count() == 0)
            {
                var registerResult = client.RegisterNewThread(model.UserLogin, model.Topic, model.Content, model.Tags);
                if (registerResult.Item1)
                {
                    return RedirectToAction("ShowThread", new { threadId = registerResult.Item2 });
                }
                else
                {
                    ModelState.AddModelError("", "Nastąpił błąd, spróbuj ponownie później");
                }
            }
            return RedirectToAction("NewThread", model);
        }

        public ViewResult ShowThread(int threadId, MessageModel mmodel = null)
        {
            ViewThreadModel model = new ViewThreadModel() { ThreadId = threadId };
            if (mmodel != null)
            {
                mmodel.ThreadId = threadId;
                model.MessageModel = mmodel;
            }
            else
            {
                model.MessageModel = new MessageModel();
            }

            DatabaseAccess client = DatabaseAccess.Instance;
            var TitleAndTags = client.GetThreadTitleAndTags(threadId);
            model.ThreadTopic = TitleAndTags.Item1;
            model.Tags = TitleAndTags.Item2;
            var messages = client.GetThreadContent(threadId);
            model.Messages = messages.Select(s => new ViewThreadModel.SingleMessage() { Content = s.Item1, Author = s.Item4, Score = s.Item3, PostDate = s.Item2, OrdNum = s.Item5 }).ToList();

            return View("ViewThread",model);
        }

        public ActionResult DeleteThread(int threadId)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            client.DeleteThread(threadId);

            return RedirectToAction("Index", "Home",new { message = "Wątek pomyślnie usunięty!"});

        }
    }
}

TAI_Forum/Views/Home/Index.cshtml
@using System.Web
@model TAI_Forum.Models.IndexModel
@{
    ViewBag.Title = "Strona główna";
}

@if (Model.IndexMessage != null)
{
    <div class="alert alert-success alert-dismissible fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @Model.IndexMessage
    </div>
}

<div class="jumbotron">
    <h1>Forum nietematyczne</h1>
    <p class="lead">Dyskutuj z innymi i dziel się opinią. Dowolną opinią! </p>
</div>

@if (Model.IsLoggedIn)
{
    <div class="row newThreadBtn">
        @Html.ActionLink("Załóż nowy temat", "DisplayNewThread", "Threads", null, new { @class = "btn btn-primary newThreadBtnBtn" })
    </div>
}

@foreach (var t in Model.ThreadsList)
{
    <div class="row singleArticle">
        <div class="authorBox">
            Autor:<br/>
            @t.Author
        </div>
        <h2><strong>@Html.ActionLink(t.Topic, "ShowThread", "Threads", new { threadId = t.Id }, null)</strong></h2>
        <p class="lead customLead">
            @t.ContentLead ...
        </p>
        <p>Tagi: <strong>@t.Tags</strong></p>
        @if (Model.IsAdmin)
        {
            @Html.ActionLink("Usuń wątek", "DeleteThread", "Threads", new { threadId = t.Id }, new { @class = "btn btn-primary delThreadBtn" })
        }
    </div>
}

TAI_Forum/Views/Home/SearchResult.cshtml
@model TAI_Forum.Models.SearchModel
@{ 
    ViewBag.Title = "Wyniki wyszukiwania dla:"+Model.Tag;
}

<div class="jumbotron">
    <p class="lead">Wyniki wyszukiwania dla tagu: @Model.Tag </p>
</div>

@foreach (var t in Model.SearchThreadsList)
{
    <div class="row singleArticle">
        <div class="authorBox">
            Autor:<br />
            @t.Author
        </div>
        <h2><strong>@Html.ActionLink(t.Topic, "ShowThread", "Threads", new { threadId = t.Id }, null)</strong></h2>
        <p class="lead customLead">
            @t.ContentLead ...
        </p>
        <p>Tagi: <strong>@t.Tags</strong></p>
        @if (Model.IsAdmin)
        {
            @Html.ActionLink("Usuń wątek", "DeleteThread", "Threads", new { threadId = t.Id }, new { @class = "btn btn-primary delThreadBtn" })
        }
    </div>
}