TAI_Forum/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TAI_Forum.Models;
using TAI_Forum.Infrastructure;

namespace TAI_Forum.Controllers
{
    public class MessagesController : Controller
    {
        public ActionResult CreateNewMessage(MessageModel model)
        {
            model.ErrorMessage = null;
            DatabaseAccess client = DatabaseAccess.Instance;
            if (model.NewMessage == null)
                model.ErrorMessage = "Brak treści!";
            if (model.ErrorMessage == null)
            {
                var msgResult = client.AddNewMessage(model.ThreadId, model.NewMessage, model.UserLogin);
                if (msgResult.Item1)
                {
                    return RedirectToAction("ShowThread", "Threads",new { threadId = msgResult.Item2 });
                }
                else
                {
                    model.ErrorMessage = "Brak treści!";
                }
            }
            return RedirectToAction("ShowThread", "Threads", new { threadId = model.ThreadId, mmodel = model });
        }

        public ActionResult UpvoteMessage(int threadId, int ordNum)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            int result = client.ScoreMessage(threadId, ordNum, '+');
            return RedirectToAction("ShowThread", "Threads", new { threadId = result });
        }

        public ActionResult DownvoteMessage(int threadId, int ordNum)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            int result = client.ScoreMessage(threadId, ordNum, '-');
            return RedirectToAction("ShowThread", "Threads", new { threadId = result });
        }

        public ActionResult DeleteMessage(int threadId, int ordNum)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            var result = client.DeleteMessage(threadId, ordNum);
            if(result.Item1)
                return RedirectToAction("ShowThread", "Threads", new { threadId = result.Item2 });
            else
                return RedirectToAction("ShowThread", "Threads", new { threadId = threadId });
        }
    }
}

TAI_Forum/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TAI_Forum.Models;
using TAI_Forum.Infrastructure;

namespace TAI_Forum.Controllers
{
    public class ThreadsController : Controller
    {
        public ViewResult DisplayNewThread()
        {
            return View("NewThread", new NewThreadModel());
        }

        public ActionResult CreateNewThread(NewThreadModel model)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            if (model.Topic == null)
                ModelState.AddModelError("", "Brak nazwy wątku!");
            if (model.Content == null)
                ModelState.AddModelError("", "Treść nie może być pusta");
            if (ModelState.Values.SelectMany(s => s.Errors).Count() == 0)
            {
                var registerResult = client.RegisterNewThread(model.UserLogin, model.Topic, model.Content, model.Tags);
                if (registerResult.Item1)
                {
                    return RedirectToAction("ShowThread", new { threadId = registerResult.Item2 });
                }
                else
                {
                    ModelState.AddModelError("", "Nastąpił błąd, spróbuj ponownie później");
                }
            }
            return RedirectToAction("NewThread", model);
        }

        public ViewResult ShowThread(int threadId, MessageModel mmodel = null)
        {
            ViewThreadModel model = new ViewThreadModel() { ThreadId = threadId };
            if (mmodel != null)
            {
                mmodel.ThreadId = threadId;
                model.MessageModel = mmodel;
            }
            else
            {
                model.MessageModel = new MessageModel();
            }

            DatabaseAccess client = DatabaseAccess.Instance;
            var TitleAndTags = client.GetThreadTitleAndTags(threadId);
            model.ThreadTopic = TitleAndTags.Item1;
            model.Tags = TitleAndTags.Item2;
            var messages = client.GetThreadContent(threadId);
            model.Messages = messages.Select(s => new ViewThreadModel.SingleMessage() { Content = s.Item1, Author = s.Item4, Score = s.Item3, PostDate = s.Item2, OrdNum = s.Item5 }).ToList();

            return View("ViewThread",model);
        }

        public ActionResult DeleteThread(int threadId)
        {
            DatabaseAccess client = DatabaseAccess.Instance;
            client.DeleteThread(threadId);

            return RedirectToAction("Index", "Home",new { message = "Wątek pomyślnie usunięty!"});

        }
    }
}

TAI_Forum/Views/Threads/NewThread.cshtml
@using System.Web
@model TAI_Forum.Models.NewThreadModel

@{ ViewBag.Title = "Nowy wątek"; }

@using (Html.BeginForm("CreateNewThread", "Threads", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Utwórz nowy wątek</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Topic, new { @class = "control-label" })
        <div class="threadParthBox">
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control threadTextBox" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Content, new { @class = "control-label" })
        <div class="threadParthBox">
            @Html.TextAreaFor(m => m.Content, new { @class = "form-control threadTextArea" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Tags, new { @class = "control-label" })
        <div class="threadParthBox">
            @Html.TextBoxFor(m => m.Tags, new { @class = "form-control threadTextBox" })
        </div>
    </div>
    <div class="form-group">
        <div class="">
            <input type="submit" class="btn btn-default" value="Utwórz wątek" />
        </div>
    </div>
}

TAI_Forum/Views/Threads/ViewThread.cshtml
@using System.Web
@model TAI_Forum.Models.ViewThreadModel
@{
    ViewBag.Title = Model.ThreadTopic;
}

<div class="jumbotron threadTitleBox">
    <h1>@Model.ThreadTopic</h1>
    <p>@Model.Tags</p>
</div>


@foreach (var t in Model.Messages)
{
    <div class="row singleArticle">
        <div class="authorBox">
            Autor: @t.Author
        </div>
        <div class="lead customLead">
            @(new HtmlString(t.Content.Replace(Environment.NewLine,"<br />")))
        </div>
        @if (Model.IsLoggedIn && !Model.IsAdmin)
        {
            <div class="scoreBox">
               @Html.ActionLink('\u21d1'.ToString(), "UpvoteMessage", "Messages", new { threadId = Model.ThreadId, ordNum = t.OrdNum }, new { @class = "upvoteBtn" })  
               @t.Score 
               @Html.ActionLink('\u21d3'.ToString(), "DownvoteMessage", "Messages", new { threadId = Model.ThreadId, ordNum = t.OrdNum }, new { @class = "downvoteBtn" })
            </div>
        }        
        @if (Model.IsAdmin)
        {
            <div class="deMsglBox">
                @Html.ActionLink("Usuń wiadomość", "DeleteMessage", "Messages", new { threadId = Model.ThreadId, ordNum = t.OrdNum }, new { @class = "btn btn-primary delThreadBtn" })
            </div>
        }
        <div class="dateBox">
            Wysłany: @t.PostDate.Substring(0, 19)
        </div>
    </div>
}
@Html.Partial("_NewMessagePartial", Model.MessageModel)

TAI_Forum/Views/Threads/_NewMessagePartial.cshtml
@model TAI_Forum.Models.MessageModel

@if (Model.IsLoggedIn)
{
    using (Html.BeginForm("CreateNewMessage", "Messages", FormMethod.Post, new { role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>Twoja odpowiedź</h4>
        <hr />
        <div class = "text-danger">@((Model.ErrorMessage!=null)? Model.ErrorMessage : "")</div>
        <div class="form-group">
            @Html.LabelFor(m => m.NewMessage, new { @class = "control-label" })
            <div class="threadParthBox">
                @Html.TextAreaFor(m => m.NewMessage, new { @class = "form-control threadTextArea" })
            </div>
        </div>
        @Html.Hidden("ThreadId", Model.ThreadId)
        <div class="form-group">
            <div class="">
                <input type="submit" class="btn btn-default" value="Dodaj odpowiedź" />
            </div>
        </div>
    }
}